# Generated by Django 3.0.3 on 2020-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200601_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='name',
            field=models.CharField(default='Document', max_length=100),
        ),
    ]
