# Generated by Django 3.0.3 on 2020-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_post',
            name='title',
            field=models.CharField(default='Post Title', max_length=100),
        ),
    ]
