# Generated by Django 3.0.3 on 2020-06-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projects_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
