# Generated by Django 3.0.3 on 2020-06-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200601_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects_Post',
            new_name='ProjectsPost',
        ),
    ]
