# Generated by Django 3.0.3 on 2020-06-03 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20200601_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectspost',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='projectspost',
            unique_together={('author', 'message')},
        ),
    ]
